[package]
name = "sigset"
version = "0.1.0"
authors = ["19h <kenan@sig.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
